name: GitHub Actions Demo
run-name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Name to Deploy'
        type: string
        required: true
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
          
      - name: Set Registry Value
        run: |
          /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/node /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/npm config set "@se:registry" "https://nexus.tools.struxurewarecloud.com/repository/app-services-npm/" &&
          /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/node /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/npm config set "//nexus.tools.struxurewarecloud.com/repository/app-services-npm/:_authToken" "${{ secrets.authToken }}"

      - name: Install Dependencies
        run: |
          /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/node /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/npm install
          
      - name: Lint Code Scan
        run: |
          export CHROME_BIN=/usr/bin/google-chrome &&
          /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/node /home/ubuntu/actions-runner/_work/dsc-poc/dsc-poc/node_modules/@angular/cli/bin/ng.js lint
          
      - name: Test
        run: |
          /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/node /home/ubuntu/actions-runner/_work/dsc-poc/dsc-poc/node_modules/@angular/cli/bin/ng.js test --no-watch --code-coverage --browsers ChromeHeadless

      - name: Build Artifact
        if: always()
        run: |
          /home/ubuntu/actions-runner/_work/_tool/node/18.12.1/x64/bin/node /home/ubuntu/actions-runner/_work/dsc-poc/dsc-poc/node_modules/@angular/cli/bin/ng.js build

      - name: List files in the repository after build
        run: |
          ls ${{ github.workspace }}
